# Generated by Django 6.0 on 2025-12-27 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('privacy', models.CharField(choices=[('Private', 'private'), ('Public', 'public'), ('Followers', 'followers')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='home.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Like_comment_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.profile')),
                ('likes_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='home.profile')),
            ],
            options={
                'unique_together': {('likes_count', 'comments_count')},
            },
        ),
    ]
